# Generated by Django 3.0.3 on 2020-09-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixinfo',
            name='fixmanager',
        ),
        migrations.RemoveField(
            model_name='fixinfo',
            name='fixputdate',
        ),
        migrations.RemoveField(
            model_name='fixinfo',
            name='ifover',
        ),
        migrations.RemoveField(
            model_name='fixinfo',
            name='incubator_incuno',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='releasestime',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='sdescription',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='simage',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='sphonenum',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='splant',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='sprice',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='sscore',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='user_userid',
        ),
        migrations.AddField(
            model_name='fixinfo',
            name='fname',
            field=models.CharField(db_column='fname', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fixinfo',
            name='score',
            field=models.CharField(db_column='score', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fixinfo',
            name='state',
            field=models.BooleanField(db_column='state', default=None),
        ),
        migrations.AddField(
            model_name='sellpost',
            name='sname',
            field=models.CharField(db_column='sname', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sellpost',
            name='state',
            field=models.BooleanField(db_column='state', default=None),
        ),
        migrations.AddField(
            model_name='sellpost',
            name='stype',
            field=models.CharField(db_column='stype', max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='User_plant',
            fields=[
                ('id', models.CharField(db_column='No', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('time', models.DateTimeField(blank=True, db_column='time', null=True)),
                ('num', models.IntegerField(db_column='num', null=True)),
                ('point', models.IntegerField(db_column='point', null=True)),
                ('case', models.CharField(db_column='case', max_length=45, null=True)),
                ('user_userid', models.ForeignKey(blank=True, db_column='User_userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
            ],
            options={
                'db_table': 'User_plant',
                'managed': True,
            },
        ),
    ]
