# Generated by Django 3.0.3 on 2020-10-20 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(default='', max_length=20)),
                ('temperature', models.CharField(default='', max_length=20)),
                ('light', models.CharField(default='', max_length=20)),
                ('pres', models.CharField(default='', max_length=20)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.CharField(max_length=500)),
                ('incubator_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Advice',
                'ordering': ('time',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(default='', max_length=20)),
                ('temperature', models.CharField(default='', max_length=20)),
                ('light', models.CharField(default='', max_length=20)),
                ('pres', models.CharField(default='', max_length=20)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('incubator_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Control',
                'ordering': ('time',),
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='fixlist',
            old_name='incubator',
            new_name='incubator_id',
        ),
        migrations.AddField(
            model_name='fixlist',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incubatorhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 16, 54, 44, 173726)),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='curTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.ImageField(default='avator.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 16, 54, 44, 169727)),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=20)),
                ('sensor_name', models.CharField(max_length=20)),
                ('sensor_state', models.BooleanField(default=True)),
                ('delivery_time', models.DateTimeField(default='2020-01-01 00:00:00')),
                ('service_life', models.IntegerField(default=24)),
                ('sensor_value', models.CharField(default='0', max_length=20)),
                ('incubator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Incubator')),
            ],
            options={
                'db_table': 'Sensor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=20)),
                ('device_name', models.CharField(max_length=20)),
                ('device_state', models.BooleanField(default=True)),
                ('delivery_time', models.DateTimeField(default='2020-01-01 00:00:00')),
                ('service_life', models.IntegerField(default=24)),
                ('incubator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Incubator')),
            ],
            options={
                'db_table': 'Device',
                'managed': True,
            },
        ),
    ]
