# Generated by Django 3.0.3 on 2020-10-20 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201020_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advice',
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='incubator_id',
        ),
        migrations.RenameField(
            model_name='fixlist',
            old_name='incubator_id',
            new_name='incubator',
        ),
        migrations.RemoveField(
            model_name='fixlist',
            name='state',
        ),
        migrations.RemoveField(
            model_name='incubatorhistory',
            name='image',
        ),
        migrations.AlterField(
            model_name='camera',
            name='data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 17, 26, 49, 572591)),
        ),
        migrations.AlterField(
            model_name='camera',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 26, 49, 572591)),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 17, 26, 49, 570040)),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='incubator_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='curTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 26, 49, 572591)),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='humidity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='light',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='plant',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lightsensor',
            name='data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lightsensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lightsensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 17, 26, 49, 569674)),
        ),
        migrations.AlterField(
            model_name='lightsensor',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mark',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 17, 26, 49, 570040)),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 17, 26, 49, 570040)),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='state',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 26, 49, 567674)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 26, 49, 567674)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
