# Generated by Django 3.1.1 on 2020-10-11 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201011_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixlist',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 18, 37, 684692)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 18, 37, 679706)),
        ),
    ]
