# Generated by Django 3.0.3 on 2020-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('type_title', models.CharField(max_length=20, verbose_name='优势标题')),
                ('type_desc', models.CharField(max_length=200, verbose_name='优势详情')),
            ],
            options={
                'verbose_name': '产品优势',
                'verbose_name_plural': '产品优势',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('image', models.ImageField(upload_to='static/home_images', verbose_name='轮播图')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncubatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('image', models.ImageField(upload_to='static/incu_images', verbose_name='图片')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('description', models.CharField(max_length=200, verbose_name='详细描述')),
            ],
            options={
                'verbose_name': '培养箱介绍',
                'verbose_name_plural': '培养箱介绍',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('policy_link', models.CharField(max_length=200, verbose_name='相关链接')),
                ('link_type', models.CharField(choices=[('国家政策', '国家政策'), ('中草药培养指南', '中草药培养指南'), ('培养箱使用手册', '培养箱使用手册'), ('草药市场行情', '中草药培养指南')], default='相关政策', max_length=50, verbose_name='链接类型')),
            ],
            options={
                'verbose_name': '相关链接',
                'verbose_name_plural': '相关链接',
                'managed': True,
            },
        ),
    ]
