# Generated by Django 3.0.3 on 2020-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='链接标题'),
        ),
    ]
