# Generated by Django 3.0.3 on 2020-11-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_manage', '0002_link_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('国家政策', '国家政策'), ('中草药培养指南', '中草药培养指南'), ('培养箱使用手册', '培养箱使用手册'), ('草药市场行情', '草药市场行情')], default='相关政策', max_length=50, verbose_name='链接类型'),
        ),
    ]
