# Generated by Django 3.0.3 on 2020-10-21 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201021_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='curTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='当前记录时间'),
        ),
        migrations.AlterField(
            model_name='lightsensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 10, 50, 51, 426349), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 50, 51, 410722)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 50, 51, 410722)),
        ),
    ]
