# Generated by Django 3.0.3 on 2021-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210121_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubator',
            name='schedule',
            field=models.CharField(choices=[('用户申请中，待通过', '用户申请中，待通过'), ('配送中', '配送中'), ('正在使用', '正在使用')], default='正在使用', max_length=20, verbose_name='培养箱情况'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='career',
            field=models.CharField(choices=[('药农', '药农'), ('教师', '教师'), ('技术人员', '技术人员'), ('学生', '学生'), ('游客', '游客'), ('其他', '其他')], default='其他', max_length=20, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='company_or_school',
            field=models.CharField(default='未知', max_length=100, verbose_name='公司或学校'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='phone',
            field=models.CharField(default='未知', max_length=20, verbose_name='电话号码'),
        ),
    ]
