# Generated by Django 3.0.3 on 2021-01-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210121_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='schedule',
            field=models.CharField(choices=[('用户申请中，待通过', '用户申请中，待通过'), ('配送中', '配送中'), ('正在使用', '正在使用'), ('用户信息不全，拒绝通过', '用户信息不全，拒绝通过')], default='用户申请中，待通过', max_length=20, verbose_name='订单状态'),
        ),
    ]
