# Generated by Django 3.0.3 on 2020-10-21 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201021_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'managed': True, 'verbose_name': '照相机', 'verbose_name_plural': '照相机'},
        ),
        migrations.AlterModelOptions(
            name='fixlist',
            options={'managed': True, 'verbose_name': '维修订单', 'verbose_name_plural': '维修订单'},
        ),
        migrations.AlterModelOptions(
            name='humiditysensor',
            options={'managed': True, 'verbose_name': '湿度传感器', 'verbose_name_plural': '湿度传感器'},
        ),
        migrations.AlterModelOptions(
            name='incubator',
            options={'managed': True, 'verbose_name': '培养箱', 'verbose_name_plural': '培养箱'},
        ),
        migrations.AlterModelOptions(
            name='incubatorhistory',
            options={'managed': True, 'verbose_name': '历史记录', 'verbose_name_plural': '历史记录'},
        ),
        migrations.AlterModelOptions(
            name='lightsensor',
            options={'managed': True, 'verbose_name': '光照传感器', 'verbose_name_plural': '光照传感器'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'managed': True, 'verbose_name': '植物', 'verbose_name_plural': '植物'},
        ),
        migrations.AlterModelOptions(
            name='pressuresensor',
            options={'managed': True, 'verbose_name': '压强传感器', 'verbose_name_plural': '压强传感器'},
        ),
        migrations.AlterModelOptions(
            name='temperaturesensor',
            options={'managed': True, 'verbose_name': '温度传感器', 'verbose_name_plural': '温度传感器'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': '使用用户', 'verbose_name_plural': '使用用户'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 11, 8, 14, 626047), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 11, 8, 14, 626047), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 11, 8, 14, 626047), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='incubatorhistory',
            name='curTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 11, 8, 14, 626047), verbose_name='当前记录时间'),
        ),
        migrations.AlterField(
            model_name='lightsensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 11, 8, 14, 615101), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 11, 8, 14, 615101), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 11, 8, 14, 615101), verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 11, 8, 14, 615101)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 11, 8, 14, 615101)),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
