# Generated by Django 3.0.3 on 2021-01-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userorder_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubator',
            name='incubator_type',
            field=models.CharField(default='ZY-001', max_length=20, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='state',
            field=models.BooleanField(default=False, verbose_name='是否正常运行'),
        ),
    ]
