# Generated by Django 3.0.3 on 2021-01-22 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210122_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=20, verbose_name='姓名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('email', models.CharField(default='未知', max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(default='未知', max_length=20, verbose_name='电话')),
                ('describe', models.CharField(default='未知', max_length=1000, verbose_name='反馈描述')),
                ('issue_state', models.CharField(choices=[('未处理', '未处理'), ('已处理', '已处理')], default='未处理', max_length=20, verbose_name='状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserOrder')),
            ],
            options={
                'verbose_name': '申请反馈',
                'verbose_name_plural': '申请反馈',
                'db_table': 'OrderIssue',
                'managed': True,
            },
        ),
    ]
