# Generated by Django 3.0.3 on 2021-03-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210327_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='avator.jpg', upload_to='static/img/personInfo'),
        ),
    ]
