# Generated by Django 3.0.3 on 2021-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210327_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubator',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
